#!/bin/bash
#
# postinstall script Legacy-Video-patch 10.15
#
# By chris1111

cp -R /"$3"/tmp/InstallKext/GeForceTesla.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/GeForceTeslaGLDriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/GeForceTeslaVADriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/NDRVShim.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/NVDANV50HalTesla.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/NVDAResmanTesla.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/IOSurface.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000Graphics.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsGA.plugin "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsGLDriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsVADriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelSNBGraphicsFB.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelSNBVA.bundle "${3}/System/Library/Extensions/"



cp -R /"$3"/tmp/GPUOpenGLFramework/OpenGL.framework "${3}/System/Library/Frameworks/"
cp -R /"$3"/tmp/GPUOpenGLFramework/GPUSupport.framework "${3}/System/Library/PrivateFrameworks/"

cp -R /"$3"/tmp/CoreDisplayFramework/CoreDisplay.framework "${3}/System/Library/Frameworks/"
cp -R /"$3"/tmp/SkyLightframework/SkyLight.framework "${3}/System/Library/PrivateFrameworks/"


touch "${3}/System/Library/Extensions/"
chmod -R 755 "${3}/System/Library/Extensions/"
chown -R root:wheel "${3}/System/Library/Extensions/"
kextcache -system-prelinked-kernel
kextcache -system-caches

rm -rf /"$3"/tmp/InstallKext
rm -rf /"$3"/tmp/CoreDisplayFramework
rm -rf /"$3"/tmp/GPUOpenGLFramework
rm -rf /"$3"/tmp/SkyLightframework
rm -rf /"$3"/tmp/Install

exit 
