#!/bin/bash
#
# postinstall script Legacy-Video-patch 10.15
#
# By chris1111

cp -R /"$3"/tmp/InstallKext/GeForceTesla.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/GeForceTeslaGLDriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/GeForceTeslaVADriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/NDRVShim.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/NVDANV50HalTesla.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/NVDAResmanTesla.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/IOSurface.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000Graphics.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsGA.plugin "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsGLDriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsVADriver.bundle "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelSNBGraphicsFB.kext "${3}/System/Library/Extensions/"
cp -R /"$3"/tmp/InstallKext/AppleIntelSNBVA.bundle "${3}/System/Library/Extensions/"



cp -R /"$3"/tmp/GPUOpenGLFramework/OpenGL.framework "${3}/System/Library/Frameworks/"
cp -R /"$3"/tmp/GPUOpenGLFramework/GPUSupport.framework "${3}/System/Library/PrivateFrameworks/"

cp -R /"$3"/tmp/CoreDisplayFramework/CoreDisplay.framework "${3}/System/Library/Frameworks/"
cp -R /"$3"/tmp/SkyLightframework/SkyLight.framework "${3}/System/Library/PrivateFrameworks/"

sudo chmod -R 755 /System/Library/PrivateFrameworks/GPUSupport.framework
sudo chown -R 0:0 /System/Library/PrivateFrameworks/GPUSupport.framework
sudo chmod -R 755 /System/Library/Frameworks/OpenGL.framework
sudo chown -R 0:0 /System/Library/Frameworks/OpenGL.framework

sudo chmod -R 755 /System/Library/Frameworks/CoreDisplay.framework
sudo chown -R 0:0 /System/Library/Frameworks/CoreDisplay.framework

sudo chmod -R 755 /System/Library/PrivateFrameworks/SkyLight.framework
sudo chown -R 0:0 /System/Library/PrivateFrameworks/SkyLight.framework



sudo touch "${3}/System/Library/Extensions/"
sudo chmod -R 755 "${3}/System/Library/Extensions/"
sudo chown -R root:wheel "${3}/System/Library/Extensions/"
sudo kextcache -system-prelinked-kernel
sudo kextcache -system-caches

sudo rm -rf /"$3"/tmp/InstallKext
sudo rm -rf /"$3"/tmp/CoreDisplayFramework
sudo rm -rf /"$3"/tmp/GPUOpenGLFramework
sudo rm -rf /"$3"/tmp/SkyLightframework
sudo rm -rf /"$3"/tmp/Install

exit 